### ISSUE TITLE
[Bug]: Warning: Error in req_perform: Failed to perform HTTP request.

### ISSUE THREAD

**Issue by chrisumphlett** [Appsilon/LogAnalyzer#10] opened 2024-06-04 20:13 UTC
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Platform and OS Version

Windows

### What happened?

I know that my api key is valid (I can make manual connections to the Connect server API). But I don't know how to troubleshoot this error.
App starts to load and then closes with this error:

```
Warning in `<reactive:state$selected_app>`(...) :
  restarting interrupted promise evaluation
Warning: Error in req_perform: Failed to perform HTTP request.
Caused by error in `curl::curl_fetch_memory()`:
! Could not resolve host: {myconnectdomain}.com__api__
```

### Steps to reproduce

1. Open LogAnalyzer Project
2. Open `app.R`
3. Hit 'Run App' button

### Expected behavior

Have app successfully load and show logs

**Comment by DeepanshKhurana** [comment] 2024-06-06 06:05
Hey, @chrisumphlett. Thanks for raising this. It seems the URL that's being created is missing a `/`. For context, the way things are setup in the app, the `get_api_url` function to be specific, is as follows:

```r
get_api_url <- function(
  host = Sys.getenv("CONNECT_SERVER"),
  endpoint = "content",
  version = "v1"
) {
  glue("{host}__api__/{version}/{endpoint}/")
}
```

**For context:** Now, the reason we don't have a `/` after `{host}` in the `glue` bit is because when Posit Connect sets the `CONNECT_SERVER` envvar, it does it _with_ the `/` after the url. The decision to not handle this here (maybe through an _if / exists, use it, else add it manually_) was made because missing the `/` at the end would only happen when testing locally.

Can you try modifying `{myconnectdomain}.com` to `{myconnectdomain}.com/` and check if it works?

**Comment by chrisumphlett** [comment] 2024-06-06 12:37
Thanks. I added that and now I'm getting errors with the `jsonlite` package. 
I am not a `rhino` nor `renv` user, and the need to install _every single R package_ before I got started was already a burden. It makes me not want to try troubleshooting this because I don't know what I don't know.

![image](https://github.com/Appsilon/LogAnalyzer/assets/7210482/fcec4c46-1049-4826-8ccd-6b7132dbe62c)

**Comment by DeepanshKhurana** [comment] 2024-06-06 17:36
I understand.

The way things are setup, a `renv::restore()` should have done the trick. But, of course, it did not work. Just so I can investigate things further, can you share the output to `sessionInfo()`?

**Comment by chrisumphlett** [comment] 2024-06-06 19:32
```
> sessionInfo()
R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22000)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.0    tools_4.3.0       rstudioapi_0.15.0 rhino_1.7.0       renv_1.0.3   
```

**Comment by DeepanshKhurana** [comment] 2024-06-07 12:01
Thanks, @chrisumphlett, for sharing this. From what I can see, things look to be in order. I tried to install everything in a Windows environment today. The goal of `renv` is to have reproducibility. All the packages that get installed with it ensure that the app works exactly as it does on both ends. But it seems it does not travel well since I did have to install some packages manually. Still, the app does work for me in a Windows environment too (after resolving some package dependencies).

Just to make sure everything is in order, can you confirm that you followed the steps as per [the guide on the blog](https://www.appsilon.com/post/introducing-loganalyzer?utm_source=social&utm_medium=linkedin&utm_campaign=blog&utm_term=appsilon-account) or [GitHub](https://www.appsilon.com/post/introducing-loganalyzer?utm_source=social&utm_medium=linkedin&utm_campaign=blog&utm_term=appsilon-account): 

- `renv::restore()`
- Set `CONNECT_SERVER` and `CONNECT_API_KEY` manually in a `.Renviron` file or using `usethis::edit_r_environ()`
- Restart R Session
- `shiny::runApp()`

**Comment by chrisumphlett** [comment] 2024-06-08 10:51
No change

```
> renv::restore()
- The library is already synchronized with the lockfile.

Restarting R session...

- Project '~/GitHub/LogAnalyzer' loaded. [renv 1.0.3]
> shiny::runApp()
Loading required package: shiny


Warning: Error in : lexical error: invalid char in json text.
                                       <!-- Copyright (C) Microsoft Co
                     (right here) ------^
```

**Comment by DeepanshKhurana** [comment] 2024-06-10 05:43
> No change
> 
> ```
> > renv::restore()
> - The library is already synchronized with the lockfile.
> 
> Restarting R session...
> 
> - Project '~/GitHub/LogAnalyzer' loaded. [renv 1.0.3]
> > shiny::runApp()
> Loading required package: shiny
> 
> 
> Warning: Error in : lexical error: invalid char in json text.
>                                        <!-- Copyright (C) Microsoft Co
>                      (right here) ------^
> ```

Thanks for trying this, @chrisumphlett. Another thing to check is the Posit Connect version that the applications are deployed on? Maybe, there's a difference with the API versions between Connect versions. A quick way to check it is as follows.

```r
conn <- connectapi::connect()
conn$server_settings()$version
```

**Edit:** If we can narrow this down, we could actually handle this well in the application to check for Connect versions and fail gracefully, so to speak. So, this is really valuable feedback. I appreciate you trying my suggestions out in this thread. Thank you.

**Comment by chrisumphlett** [comment] 2024-06-10 12:53
that helped reveal a problem-- the `connectapi` package wasn't installed. 

```
> conn <- connectapi::connect()
Defining Connect with server: https://rstudio.techsmith.com/
> conn$server_settings()$version
[1] "2024.01.0"
```

After installing it, I get a new error when trying to launch the app.

```
> shiny::runApp()
Loading required package: shiny
Error: C stack usage  15923488 is too close to the limit
```

**Comment by DeepanshKhurana** [comment] 2024-06-11 05:29
> that helped reveal a problem-- the `connectapi` package wasn't installed.
> 
> ```
> > conn <- connectapi::connect()
> Defining Connect with server: https://rstudio.techsmith.com/
> > conn$server_settings()$version
> [1] "2024.01.0"
> ```
> 
> After installing it, I get a new error when trying to launch the app.
> 
> ```
> > shiny::runApp()
> Loading required package: shiny
> Error: C stack usage  15923488 is too close to the limit
> ```

There's another good thing in this whole mix that has happened. Since I can see your URL now, it seems you have Microsoft oAuth (possibly EntraID?) on the Connect instance and that's preventing the Posit API from accessing the correct data. The login page is somewhat in the middle. I'm not sure how Posit's API is configured in this regard (as in how they fetch the data) but it seems that opening the `{CONNECT_SERVER}/__api__/` for public connections in the network configuration could work somehow. Although, I understand how that may not be desirable and that is fair.

For making things slightly easier for future users, we are planning to add a validation layer to show a more user-friendly error messages if the first API call does not send a desirable output. At least, it will make things less frustrating.

That said, maybe having the app deployed _in_ the Posit Connect environment could work since the user will already be authenticated. Although, that is a long shot and I know it may not be desirable either.

But my hunch is on the oAuth / 2FA that is in place after seeing the link and where it redirects.

**Comment by chrisumphlett** [comment] 2024-06-11 10:41
Yes -- we are using SSO through what is now called MSFT Entra. 
I tried deploying to connect, get a similar error: `Error: C stack usage  7973524 is too close to the limit`

**Comment by DeepanshKhurana** [comment] 2024-06-11 10:49
> Yes -- we are using SSO through what is now called MSFT Entra. I tried deploying to connect, get a similar error: `Error: C stack usage 7973524 is too close to the limit`

Yeah, so what is happening here is that the SSO is what's coming in between the API. Unfortunately, the way the `/content` endpoint gets the data (as far as I know) does not handle this effectively (from what I have understood in our discussion). In any case, we are at least going to gracefully handle this, but it is a bummer that you could not use the app. At least, yet. 

I'll try to see if I can raise an issue on the `/content` API.

**Closed as completed** 2024-06-11 10:55 UTC
Labels: bug
